### PR TITLE
Fixes array sizing for auxdn

### LINKED ISSUE #10: Array boundary error for order < 2
In functions atanhzdn and atanzdn, elements of auxdn%f(0:2) are always accessed. But it is allocated as (0:order), so will have an array boundary error if order < 2.

### PR DESCRIPTION
**Pull request by bhourahine**
In the atan and atanh routines, if order < 2, there was an array boundary error.

Closes #10

### CODE REVIEW

File: SourcesF/dualzn_mod.f90 [hunk 1]
```diff
@@ -1319,7 +1319,8 @@ pure function atanzdn(z) result(fr)
 
     den = 1.0_prec + z*z
 
-    call initialize_dualzn(auxdn)
+    allocate(auxdn%f(0:max(order,2)))
```
Comment (fpenunuri) [inline SourcesF/dualzn_mod.f90]: You're absolutely right to point out that issue — thanks for
catching it! However, I believe your suggestion is not entirely
correct, as order can be equal to 1, and using max(order, 2) in
that case would lead to unnecessary or even incorrect
computations.

What do you think about this version instead?



pure function atanzdn(z) result(fr)
  complex(prec), intent(in) :: z
  type(dualzn) :: fr
  integer :: k, i
  complex(prec) :: sumterm, den
  type(dualzn) :: auxdn

  allocate(fr%f(0:order))
  fr%f(0) = atan(z)

  if (order == 0) return

  fr%f(1) = 1.0_prec / (1.0_prec + z**2)
  if (order == 1) return

  den = 1.0_prec + z*z

  call initialize_dualzn(auxdn)
  auxdn%f(0) = den
  auxdn%f(1) = 2.0_prec * z
  auxdn%f(2) = 2.0_prec

  do k = 2, order
    sumterm = 0.0_prec
    do i = 1, k - 1
      sumterm = sumterm + binomial(k - 1, i) * auxdn%f(i) * fr%f(k - i) / den
    end do
    fr%f(k) = -sumterm
  end do
end function atanzdn

Comment (bhourahine) [reply SourcesF/dualzn_mod.f90]: Yes, definitely more efficient. I've modified the pull request to also changed atanhzdn in the same style.
